[package]
name = "human_name_nif"
version = "0.2.4"
authors = []
edition = "2018"

[lib]
name = "human_name_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
human_name = "1.2.1"
